---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: bug.84.bug.84.com.0.0.1
spec:
  refName: bug.84.bug.84.com
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - inline:
          paths:
            config/base.yaml: |
              a: a 
      template:
      - ytt:
          ignoreUnknownComments: true
          paths:
          - 'config'
          - '-'
  valuesSchema:
    openAPIv3:
      properties:
        resources:
          default: {}
          type: object
      title: bug.84.bug.84.com values schema
  version: 0.0.1
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: bug.84.bug.84.com
spec:
  displayName: bug.84
  longDescription: bug.84
  maintainers:
  - name: bug.84
  providerName: VMware
  shortDescription: bug.84
